[package]
name = "android-manifest"
version = "0.1.0"
authors = ["enfipy <enfipy@gmail.com>", "olvyko <olvyko@gmail.com>", "Adoka3710 <adicoolwest@gmail.com>"]
edition = "2018"

[dependencies]
# quick-xml = { version = "0.22", features = [ "serialize" ]}
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.8"
yaserde = "0.6"
yaserde_derive = "0.6"
# yaserde = { path = "../yaserde/yaserde" }
# yaserde_derive = { path = "../yaserde/yaserde_derive" }
xml-rs = "0.8.3"
log = "0.4"
