[package]
name = "android-manifest"
version = "0.1.0"
authors = ["David Ackerman <enfipy@gmail.com>"]
edition = "2018"

[dependencies]
quick-xml = "0.20.0"
simple-xml-builder = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4.14"
cargo_toml = "0.8.1"

[package.metadata.android]
build_targets = ["aarch64-linux-android", "armv7-linux-androideabi"]
assets = "assets"
res = "res/android"

[package.metadata.android.manifest]
apk_label = "Creator 2D"
fullscreen = true
icon = "@mipmap/ic_launcher"
target_sdk_version = 30
min_sdk_version = 16
