[package]
name = "android-manifest"
version = "0.1.0"
authors = ["enfipy <enfipy@gmail.com>", "olvyko <olvyko@gmail.com>", "Adoka3710 <adicoolwest@gmail.com>"]
edition = "2018"

[dependencies]
quick-xml = "0.20.0"
serde = { version = "1.0", features = ["derive"] }
