[package]
name = "android-manifest"
version = "0.1.0"
authors = ["DodoRare Team <dodonotrare@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_plain = "0.3"
yaserde = { git = "https://github.com/olvyko/yaserde", branch = "add-skip-ser-if" }
yaserde_derive = { git = "https://github.com/olvyko/yaserde", branch = "add-skip-ser-if" }
xml-rs = "0.8.3"
log = "0.4"
